### ISSUE TITLE
set tempo

### ISSUE THREAD

**Issue by micahvdm** [dxinteractive/ArduinoTapTempo#5]
Hi, how would one go about adding a set tempo function to this library? Need to be able to set the tempo according to the saved midi tempo in my project. At the moment it defaults to 120

**Comment by dxinteractive** [comment]
Hi, oddly enough I didn't add this in. I'm not sure when I'll get to add it, but I'm happy to accept PRs, a method called `setBPM` that accepts a float, and sets the `beatLengthMS` variable would be great.

**Comment by micahvdm** [comment]
I have submitted a PR for the setBPM addition. it is tested and working

**Comment by dxinteractive** [comment]
Hey, sorry this took so long to review and merge, done. I have too many projects!
